language: go
go:
  - 1.13.x
sudo: false

script:
  - export GOROOT=/usr/local/go
  - export GOPATH=$HOME/go
  - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  
install:
  - cd $GOPATH/src/github.com/pyx-partners/dmgd
  - GO111MODULE=on go install . ./cmd/...
  - cd $GOPATH/src/github.com/pyx-partners/dmgd/blockchain
  - go test -v -vet off
